name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Linter-run:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
