name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Linter-run:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
  Docker:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build and Push Docker Image
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: hussamgamal/node-img
          tag: v1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
